# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Genie < Formula
  desc ""
  homepage "https://genie.harshalranjhani.in"
  version "2.9.4"

  on_macos do
    url "https://github.com/harshalranjhani/genie/releases/download/v2.9.4/genie_Darwin_all.tar.gz"
    sha256 "f59822422c3a3d692b5e2d868148502780d4cb084604baa4f416c3cc9351c8d0"

    def install
      bin.install "genie"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/harshalranjhani/genie/releases/download/v2.9.4/genie_Linux_x86_64.tar.gz"
        sha256 "88783e914f497d22bd48b6812ff7944137b6c9622d1550985160a8c1adc1e9f6"

        def install
          bin.install "genie"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/harshalranjhani/genie/releases/download/v2.9.4/genie_Linux_arm64.tar.gz"
        sha256 "51e1725cc8744e4294bad8a806df40e7159d712b2ae4c988762f4cacc1c4e87e"

        def install
          bin.install "genie"
        end
      end
    end
  end
end
