# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Genie < Formula
  desc ""
  homepage "https://github.com/harshalranjhani/genie"
  version "2.0.0"

  on_macos do
    url "https://github.com/harshalranjhani/genie/releases/download/v2.0.0/genie_Darwin_all.tar.gz"
    sha256 "9bc2bbb18150c5eece8c7af0f94f690b38be0541d17dc4ccfcdfd83ca09eba10"

    def install
      bin.install "genie"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/harshalranjhani/genie/releases/download/v2.0.0/genie_Linux_x86_64.tar.gz"
        sha256 "24940b09dd56883ca32d20749d7e2cd7a02da7940cd413213e38d03f28b73bc9"

        def install
          bin.install "genie"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/harshalranjhani/genie/releases/download/v2.0.0/genie_Linux_arm64.tar.gz"
        sha256 "0905b57abfc5a57ae9c0dd734b18cc857a35fbb9bb3467c6f88034c6b1ffe241"

        def install
          bin.install "genie"
        end
      end
    end
  end
end
