# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stashr < Formula
  desc ""
  homepage "https://stashr.harshalranjhani.in"
  version "0.0.2"

  on_macos do
    url "https://github.com/harshalranjhani/stashr/releases/download/v0.0.2/stashr_0.0.2_Darwin_all.tar.gz"
    sha256 "cc2c3791209d9899072f26e22950f5d27ff342cdf3595faf1497728156ae5598"

    def install
      bin.install "stashr"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/harshalranjhani/stashr/releases/download/v0.0.2/stashr_0.0.2_Linux_x86_64.tar.gz"
      sha256 "7512f2e1b59ebeb4be0c3eb9347952205056f7721b4e7c128ad89ef7c76ceffc"
      def install
        bin.install "stashr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/harshalranjhani/stashr/releases/download/v0.0.2/stashr_0.0.2_Linux_arm64.tar.gz"
      sha256 "8266fce3ab3e1a3af23c44e46eb99f695a9d6f6d1fc02129e4d5bddf87d5ec30"
      def install
        bin.install "stashr"
      end
    end
  end
end
