# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stashr < Formula
  desc ""
  homepage "https://stashr.harshalranjhani.in"
  version "0.0.1"

  on_macos do
    url "https://github.com/harshalranjhani/stashr/releases/download/v0.0.1/stashr_0.0.1_Darwin_all.tar.gz"
    sha256 "87299e9b5cb45091d3107c6ca41894378f8bfb479fb42d1dd250d160fd380f6b"

    def install
      bin.install "stashr"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/harshalranjhani/stashr/releases/download/v0.0.1/stashr_0.0.1_Linux_x86_64.tar.gz"
      sha256 "7aecbb99c3122502db7005f7826d34add4cabde5bb591951a70670250c7b8bcb"
      def install
        bin.install "stashr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/harshalranjhani/stashr/releases/download/v0.0.1/stashr_0.0.1_Linux_arm64.tar.gz"
      sha256 "9a121bdba9244dc4ca9716c1cb2105c5ca43c52680ad109cb884137e3b210b10"
      def install
        bin.install "stashr"
      end
    end
  end
end
