# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stashr < Formula
  desc ""
  homepage "https://stashr.harshalranjhani.in"
  version "0.0.1"

  on_macos do
    url "https://github.com/harshalranjhani/stashr/releases/download/v0.0.1/stashr_0.0.1_Darwin_all.tar.gz"
    sha256 "ce9a30ab69e5b757ae681dc9c68640746b7404e97fd41b0412827a3a50e67b61"

    def install
      bin.install "stashr"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/harshalranjhani/stashr/releases/download/v0.0.1/stashr_0.0.1_Linux_x86_64.tar.gz"
      sha256 "d5e8ca0bd36b3aa7a00c365286bd274758a4ab5df0b2600b1470e3635e83a664"
      def install
        bin.install "stashr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/harshalranjhani/stashr/releases/download/v0.0.1/stashr_0.0.1_Linux_arm64.tar.gz"
      sha256 "f67f257d5a3a3c9c7e293700c7f7200b867853f9e52b74fbeb98171be85d0bf5"
      def install
        bin.install "stashr"
      end
    end
  end
end
